version: '3.8'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - linkedin-net

  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    networks:
      - linkedin-net
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - linkedin-net
      
  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - "3001:3001"
    env_file:
      - ./auth-service/.env
    networks:
      - linkedin-net

  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "3002:3002"
    env_file:
      - ./user-service/.env
    networks:
      - linkedin-net

  post-service:
    build: ./post-service
    container_name: post-service
    ports:
      - "3003:3003"
    working_dir: /usr/src/app
    env_file:
      - ./post-service/.env
    depends_on:
      - kafka
    networks:
      - linkedin-net  

  feed-service:
    build: ./feed-service
    container_name: feed-service
    ports:
      - "3004:3004"
    env_file:
      - ./feed-service/.env
    depends_on:
      - kafka
      - redis
      - post-service
      - user-service
    networks:
      - linkedin-net

  notification-service:
    build: ./notification-service 
    container_name: notification-service
    ports:
      - "3005:3005"
    env_file:
      - ./notification-service/.env
    depends_on:
      - kafka
    networks:
      - linkedin-net    

  chat-service:
    build: ./chat-service
    container_name: chat-service
    ports:
      - "3006:3006"
    env_file:
      - ./chat-service/.env
    depends_on:
      - kafka
      - redis
    networks:
      - linkedin-net    
  job-service:
    build: ./job-service
    container_name: job-service
    ports:
      - "3007:3007"
    env_file:
      - ./job-service/.env
    depends_on:
      - kafka
    networks:
      - linkedin-net

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "3000:3000"
    env_file:
      - ./api-gateway/.env
    depends_on:
      - auth-service
      - user-service
      - post-service
      - feed-service
    networks:
      - linkedin-net

networks:
  linkedin-net:
    driver: bridge
